name: CI - Automation run

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  automation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps
      - run: pytest tests/ --maxfail=3 --disable-warnings -q
